version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: url-shortener-service
    container_name: url-shortener
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - postgres_network
  db:
    image: postgres:12.16-bullseye
    container_name: postgres-db
    networks:
      - postgres_network
    ports:
      - "5432:5432"
    env_file:
      - "./db/.env"
    volumes:
      - ./db/schemas:/docker-entrypoint-initdb.d
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge
